In [1]:
import numpy as np 

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [8]:
np.arange(.4, 10.4)

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [7]:
np.arange(.4, 10.4, 0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [9]:
list(np.arange(.4, 10.4, 0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [10]:
np.linspace(1,5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [11]:
np.logspace(1,5, 10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [12]:
np.logspace(1,5, 10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [16]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
arr = np.ones((3,4))

In [20]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [21]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [24]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [25]:
np.eye(5)   #identity matices

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
arr1 = np.eye(5)

In [27]:
import pandas as pd

In [28]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [29]:
np.random.rand(2,3)  #genrate random data

array([[0.43399602, 0.34075225, 0.09036437],
       [0.81252455, 0.93182205, 0.06901446]])

In [30]:
np.random.randn(2,3)     #mean = 1, and standard deviation = 1

array([[-0.12071306, -1.42849834,  1.09032065],
       [-1.86691207, -0.41653642, -0.84862608]])

In [31]:
np.random.randint(1,5 , (3,4))

array([[2, 3, 1, 4],
       [2, 3, 4, 2],
       [3, 3, 1, 3]])

In [32]:
arr2 = np.random.randint(1,5 , (3,4))

In [33]:
arr2.size

12

In [34]:
arr2.shape

(3, 4)

In [35]:
arr2.reshape(6,2)

array([[1, 1],
       [2, 2],
       [3, 4],
       [3, 3],
       [4, 1],
       [2, 2]])

In [37]:
arr2.reshape(4,-1)

array([[1, 1, 2],
       [2, 3, 4],
       [3, 3, 4],
       [1, 2, 2]])

In [39]:
arr2.reshape(2,2,3)

array([[[1, 1, 2],
        [2, 3, 4]],

       [[3, 3, 4],
        [1, 2, 2]]])

In [40]:
arr2.reshape(2,2,3,1,1,1,1)

array([[[[[[[1]]]],



         [[[[1]]]],



         [[[[2]]]]],




        [[[[[2]]]],



         [[[[3]]]],



         [[[[4]]]]]],





       [[[[[[3]]]],



         [[[[3]]]],



         [[[[4]]]]],




        [[[[[1]]]],



         [[[[2]]]],



         [[[[2]]]]]]])

In [47]:
arr2 = np.random.randint(1,10, (5,6))

In [48]:
arr2

array([[6, 3, 9, 2, 1, 2],
       [3, 3, 2, 9, 7, 7],
       [4, 8, 6, 4, 8, 8],
       [8, 8, 3, 5, 7, 8],
       [8, 3, 9, 7, 5, 8]])

In [49]:
arr2> 8 

array([[False, False,  True, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False,  True, False, False, False]])

In [51]:
arr2[arr2>8]

array([9, 9, 9])

In [52]:
arr2

array([[6, 3, 9, 2, 1, 2],
       [3, 3, 2, 9, 7, 7],
       [4, 8, 6, 4, 8, 8],
       [8, 8, 3, 5, 7, 8],
       [8, 3, 9, 7, 5, 8]])

In [54]:
arr2[0,[0,1]]

array([6, 3])

In [55]:
arr2[2:4, [2,3]]

array([[6, 4],
       [3, 5]])

In [56]:
arr3 = np.random.randint(1,3 , (3,3))
arr4 = np.random.randint(1,3 , (3,3))

In [57]:
arr3

array([[1, 2, 1],
       [1, 2, 2],
       [2, 2, 2]])

In [58]:
arr4

array([[2, 1, 2],
       [2, 1, 1],
       [1, 1, 1]])

In [59]:
arr3 + arr4

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [60]:
#index wise multiplication
arr3*arr4

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [61]:
#matrix multiplication of array

arr3@arr4

array([[ 7,  4,  5],
       [ 8,  5,  6],
       [10,  6,  8]])

In [63]:
arr3/arr4

array([[0.5, 2. , 0.5],
       [0.5, 2. , 2. ],
       [2. , 2. , 2. ]])

In [64]:
arr3/0

C:\Users\Bhavika\AppData\Local\Temp\ipykernel_7216\1466893960.py:1: RuntimeWarning: divide by zero encountered in divide
  arr3/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [65]:
#broadcasting

arr = np.zeros((3,4))

In [66]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [68]:
a = np.array([1,2,3,4])

In [69]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [71]:
b = np.array([[3,4,5]])

In [72]:
arr+b.T

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [74]:
arr3

array([[1, 2, 1],
       [1, 2, 2],
       [2, 2, 2]])

In [75]:
np.sqrt(arr3)

array([[1.        , 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356]])

In [76]:
np.log10(arr3)

array([[0.     , 0.30103, 0.     ],
       [0.     , 0.30103, 0.30103],
       [0.30103, 0.30103, 0.30103]])

In [77]:
np.exp(arr3)

array([[2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 7.3890561 , 7.3890561 ],
       [7.3890561 , 7.3890561 , 7.3890561 ]])

In [78]:
np.min(arr1)

0.0

In [79]:
np.max(arr2)

9